#!/usr/bin/env python3
# encoding: utf-8

'''
@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT
'''

###############################################################################

from common_waf import *
import avrwaf

import os

###############################################################################


def prerequisites(ctx):
	ctx.load('avr', tooldir = avrwaf.location)
	ctx.load('avrdude', tooldir = avrwaf.location)

def options(opt):
	opt.load('c cxx')
	opt.add_option(
		'--mcu',
		dest = 'mcu',
		default = 'atmega16',
		help = 'MCU (part) for avrdude'
	)
	opt.add_option(
		'--freq',
		dest = 'freq',
		default = int(16e6),
		help = 'Working frequency MCU'
	)
	opt.add_option(
		'--programmer',
		dest = 'programmer',
		default = 'usbasp',
		help = 'Programmer/PROGRAMMER for avrdude: ' + \
			'[dragon_jtag|dragon_isp|usbasp]'
	)
	opt.add_option(
		'--app',
		dest = 'app',
		default = None,
		help = 'App to be uploaded to MCU'
	)
	opt.add_option(
		'--port',
		dest = 'port',
		default = 0,
		help = 'Programmer port number or full file name i.e. dev file ' +
			'(2, /dev/ttyUSB2, COM2)'
	)

def configure(cfg):
	# Config.
	cfg.env.MCU = cfg.options.mcu
	cfg.env.FREQ = cfg.options.freq
	#cfg.env.AVR_PATH
	cfg.env.PROGRAMMER = cfg.options.programmer

	cfg.env.HFUSE = 0xD9 # No JTAG
	cfg.env.LFUSE = 0x3F


	# bcs wide_bool()
	cfg.env.append_value('CXXFLAGS', '-Wno-overflow')

	# Tools.
	cfg.load('avr', tooldir = avrwaf.location)
	cfg.load('avrdude', tooldir = avrwaf.location)


def build(bld):
	bld.stlib(
		target = 'uart_stdio',
		source = ['uart_stdio.cpp'],
		includes = '.',
		export_includes = '.'
	)

	for code_file in glob_apps_srcs(bld):
		name = os.path.splitext(code_file)[0]
		bld.program(
			target = name + '.elf',
			features = 'avr-hex',
			source = [code_file],
			use = 'uart_stdio'
		)
		bld(
			rule = '"${OBJDUMP}" -S "${SRC}" > "${TGT[0]}"',
			target = name + '.asm',
			source = name + '.elf'
		)


###############################################################################

@after_cmd(build)
@build_context
def size(ctx):
	'''Size of firmware choosed by --app=<NAME> or all'''
	if ctx.options.app:
		a = expand_app(ctx.options.app)
		ctx(
			features = 'avr_size',
			source = 'build/' + a + '.elf'
		)

@build_context
def reset(ctx):
	'''Reset MCU'''
	ctx(features = 'avrdude_read_fuses')

@build_context
def read_fuses(ctx):
	'''Read fuses from MCU'''
	ctx(features = 'avrdude_read_fuses')

@build_context
def write_fuses(ctx):
	'''Write configured fuses from MCU'''
	ctx(
		features = 'avrdude_write_fuses',
		erase_chip = True
	)

@after_cmd(build)
@build_context
def upload(ctx):
	'''Upload firmware <NAME>.hex to MCU choosed by --app=<NAME>'''
	if ctx.options.port:
		ctx.env.PROGRAMMER_PORT = expand_port(ctx.options.port)
	if ctx.options.app:
		a = expand_app(ctx.options.app)
		ctx(
			features = 'avrdude_upload',
			source = a + '.hex'
		)

def log(ctx):
	p = expand_port(ctx.options.port)
	ctx.exec_command2('picocom -b 9600 --imap=lfcrlf {}'.format(p))

###############################################################################
